apiVersion: v1
kind: ServiceAccount
metadata:
  name: recipe-agent-service
  labels:
    {{- include "recipe-agent-service.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Chart.Name }}-role
  labels:
    {{- include "recipe-agent-service.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get"]
    resourceNames: ["pantry-chef-api"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-rolebinding
  labels:
    {{- include "recipe-agent-service.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Chart.Name }}-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: recipe-agent-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: recipe-agent-service
subjects:
- kind: ServiceAccount
  name: recipe-agent-service
  namespace: default 