apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: default
type: Opaque
data:
  db-password: {{ .Values.api.secrets.dbPassword | b64enc }}
  jwt-secret: {{ .Values.api.secrets.jwtSecret | b64enc }} 