apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: infrastructure-secrets
  namespace: infrastructure
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: kubernetes-secrets
    kind: ClusterSecretStore
  target:
    name: infrastructure-secrets
  data:
  - secretKey: postgres-password
    remoteRef:
      key: postgres-postgresql
      property: postgres-password
  - secretKey: redis-password
    remoteRef:
      key: redis
      property: redis-password
  - secretKey: rabbitmq-password
    remoteRef:
      key: rabbitmq
      property: rabbitmq-password 