apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubernetes-secrets
spec:
  provider:
    kubernetes:
      remoteNamespace: infrastructure
      auth:
        serviceAccount:
          name: external-secrets 