global:
  # Enable mutual TLS by default
  mtls:
    enabled: true

  # Configure proxy
  proxy:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

  # Configure default mesh config
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100
        zipkin:
          address: newrelic-bundle-newrelic-pixie.newrelic:9411

pilot:
  resources:
    requests:
      cpu: 500m
      memory: 2048Mi
    limits:
      cpu: 1000m
      memory: 4096Mi

  # Enable access logging
  accessLogFile: /dev/stdout

  # Configure tracing
  traceSampling: 100 