auth:
  username: user
  password: rabbitmq
  erlangCookie: cookie123

persistence:
  enabled: true
  storageClass: "local-path"
  size: 1Gi

resources:
  limits:
    memory: 512Mi
    cpu: 300m
  requests:
    memory: 256Mi
    cpu: 150m

metrics:
  enabled: true

extraPlugins: "rabbitmq_prometheus"

service:
  type: ClusterIP
  ports:
    amqp: 5672
    manager: 15672
    epmd: 4369
    dist: 25672
    metrics: 9419

readinessProbe:
  initialDelaySeconds: 20
  timeoutSeconds: 10
  periodSeconds: 30

livenessProbe:
  initialDelaySeconds: 60
  timeoutSeconds: 20
  periodSeconds: 45 