apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: pantry-chef-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pantry-chef-api
  template:
    metadata:
      labels:
        app: pantry-chef-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
            - name: grpc
              containerPort: {{ .Values.service.grpcPort }}
          env:
            - name: HTTP_PORT
              value: "{{ .Values.service.httpPort }}"
            - name: GRPC_PORT
              value: "{{ .Values.service.grpcPort }}"
            - name: DB_URL
              value: "postgresql://postgres:$(DB_PASSWORD)@postgres-postgresql.infrastructure:5432/pantry_chef?sslmode=disable"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: db-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: jwt-secret
            - name: NODE_ENV
              value: "production"
          resources:
            {{- toYaml .Values.resources | nindent 12 }} 