apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  db-password: {{ .Values.secrets.dbPassword | default "postgres" | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | default "your-jwt-secret-here" | quote }}

secrets:
  enabled: true
  refreshInterval: "1h"
  secretStore:
    name: "kubernetes-secrets"
    kind: "SecretStore"
  externalSecrets:
    - secretKey: "jwt-secret"
      remoteRef:
        key: "pantry-chef/api"
        property: "jwt-secret"
    - secretKey: "db-password"
      remoteRef:
        key: "pantry-chef/api"
        property: "db-password"
  dbPassword: postgres
  jwtSecret: your-jwt-secret-here 