apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: kubernetes-secrets
spec:
  provider:
    kubernetes:
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: default 