apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: pantry-chef-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: pantry-chef-api 