apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-routes
spec:
  hosts:
    - "*"
  gateways:
    - api-gateway  # This matches our gateway name
  http:
    - match:
        - uri:
            prefix: "/api/v1"
      route:
        - destination:
            host: api.default.svc.cluster.local  # Fully qualified service name
            port:
              number: 8000
    - match:
        - uri:
            prefix: "/health"
      route:
        - destination:
            host: api.default.svc.cluster.local
            port:
              number: 8000 