services:
  postgres:
    image: postgres:16.3
    container_name: pantry_chef_db
    platform: linux/arm64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pantry_chef
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../api/internal/platform/db/migrations:/docker-entrypoint-initdb.d/migrations
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ../../api
      dockerfile: Dockerfile
    platform: linux/arm64
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: postgresql://postgres:postgres@postgres:5432/pantry_chef?sslmode=disable
      PORT: 8000
      NODE_ENV: development
    ports:
      - "8000:8000"

volumes:
  postgres_data:
