{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-secrets
spec:
  refreshInterval: {{ .Values.secrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.secrets.secretStore.name | default "kubernetes-secrets" }}
    kind: {{ .Values.secrets.secretStore.kind | default "SecretStore" }}
  target:
    name: api-secrets
  data:
    {{- if .Values.secrets.externalSecrets }}
    {{- range .Values.secrets.externalSecrets }}
      - secretKey: {{ .secretKey }}
        remoteRef:
          key: {{ .remoteRef.key }}
          property: {{ .remoteRef.property }}
    {{- end }}
    {{- end }}
{{- end }} 