apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pantry-chef-api-network-policy
spec:
  podSelector:
    matchLabels:
      app: pantry-chef-api
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow traffic from recipe-agent-service
  - from:
    - podSelector:
        matchLabels:
          app: recipe-agent-service
    ports:
    - protocol: TCP
      port: 8000
  egress:
  # Existing RabbitMQ rule
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: infrastructure
      podSelector:
        matchLabels:
          app.kubernetes.io/name: rabbitmq
    ports:
    - protocol: TCP
      port: 5672