apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pantry-chef-api
rules:
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pantry-chef-api
subjects:
- kind: ServiceAccount
  name: pantry-chef-api
  namespace: default
roleRef:
  kind: ClusterRole
  name: pantry-chef-api
  apiGroup: rbac.authorization.k8s.io 