{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-secrets
spec:
  refreshInterval: {{ (index .Values.secrets.externalSecrets 0).refreshInterval }}
  secretStoreRef:
    name: {{ (index .Values.secrets.externalSecrets 0).secretStore }}
    kind: SecretStore
  target:
    name: api-secrets
  data:
  {{- range (index .Values.secrets.externalSecrets 0).data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
  {{- end }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  db-password: {{ .Values.secrets.dbPassword | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
{{- end }} 