# REPLACE WITH THIS INGRESS
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/v1(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 8000
      - path: /health
        pathType: Exact
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 8000 